spring:
  application:
    name: univAlarm
  profiles:
    active: ${SPRING_PROFILE:dev}
  config:
    import:
      - classpath:/universityConfig/CatholicUnivConfig.yaml
#      - classpath:config/h2.yaml
      - classpath:config/mysql.yaml
      - classpath:config/env.yaml
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

